/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhosRouteImport } from './routes/trabalhos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TrabalhosRoute = TrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/trabalhos': typeof TrabalhosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/trabalhos': typeof TrabalhosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/trabalhos': typeof TrabalhosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contato'
    | '/projetos'
    | '/sitemap.xml'
    | '/sobre'
    | '/trabalhos'
    | '/blog/$slug'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/trabalhos'
    | '/blog/$slug'
    | '/projetos/$slug'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contato'
    | '/projetos'
    | '/sitemap.xml'
    | '/sobre'
    | '/trabalhos'
    | '/blog/$slug'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TrabalhosRoute: typeof TrabalhosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhos': {
      id: '/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof TrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TrabalhosRoute: TrabalhosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
